name: Docker Image CI (nightly)

on:
  schedule:
    - cron: '35 10 * * *' # 10:35am UTC, 2:35am PST, 5:35am EST
  release:
    types: [published]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v3
    - name: Build and push the Docker image (letta)
      run: |
        docker build . \
          --file Dockerfile \
          --tag letta/letta:nightly \
          --build-arg LETTA_VERSION="nightly-$(date +%Y%m%d)-$(git rev-parse --short HEAD)"
        docker push letta/letta:nightly
